export type CountryTimezones = {
  country: string;
  timezones: string[];
};

export const countryTimezones: CountryTimezones[] = [
  { country: "Afghanistan", timezones: ["Asia/Kabul"] },
  { country: "Åland Islands", timezones: ["Europe/Mariehamn"] },
  { country: "Albania", timezones: ["Europe/Tirane"] },
  { country: "Algeria", timezones: ["Africa/Algiers"] },
  { country: "Andorra", timezones: ["Europe/Andorra"] },
  { country: "Angola", timezones: ["Africa/Luanda"] },
  { country: "Anguilla", timezones: ["America/Anguilla"] },
  {
    country: "Antarctica",
    timezones: [
      "Antarctica/Casey",
      "Antarctica/Davis",
      "Antarctica/DumontDUrville",
      "Antarctica/Mawson",
      "Antarctica/McMurdo",
      "Antarctica/Palmer",
      "Antarctica/Rothera",
      "Antarctica/Syowa",
      "Antarctica/Troll",
      "Antarctica/Vostok",
    ],
  },
  { country: "Antigua & Barbuda", timezones: ["America/Antigua"] },
  {
    country: "Argentina",
    timezones: [
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Catamarca",
      "America/Argentina/Cordoba",
      "America/Argentina/Jujuy",
      "America/Argentina/La_Rioja",
      "America/Argentina/Mendoza",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Salta",
      "America/Argentina/San_Juan",
      "America/Argentina/San_Luis",
      "America/Argentina/Tucuman",
      "America/Argentina/Ushuaia",
    ],
  },
  { country: "Armenia", timezones: ["Asia/Yerevan"] },
  { country: "Aruba", timezones: ["America/Aruba"] },
  {
    country: "Australia",
    timezones: [
      "Antarctica/Macquarie",
      "Australia/Adelaide",
      "Australia/Brisbane",
      "Australia/Broken_Hill",
      "Australia/Darwin",
      "Australia/Eucla",
      "Australia/Hobart",
      "Australia/Lindeman",
      "Australia/Lord_Howe",
      "Australia/Melbourne",
      "Australia/Perth",
      "Australia/Sydney",
    ],
  },
  { country: "Austria", timezones: ["Europe/Vienna"] },
  { country: "Azerbaijan", timezones: ["Asia/Baku"] },
  { country: "Bahamas", timezones: ["America/Nassau"] },
  { country: "Bahrain", timezones: ["Asia/Bahrain"] },
  { country: "Bangladesh", timezones: ["Asia/Dhaka"] },
  { country: "Barbados", timezones: ["America/Barbados"] },
  { country: "Belarus", timezones: ["Europe/Minsk"] },
  { country: "Belgium", timezones: ["Europe/Brussels"] },
  { country: "Belize", timezones: ["America/Belize"] },
  { country: "Benin", timezones: ["Africa/Porto-Novo"] },
  { country: "Bermuda", timezones: ["Atlantic/Bermuda"] },
  { country: "Bhutan", timezones: ["Asia/Thimphu"] },
  { country: "Bolivia", timezones: ["America/La_Paz"] },
  { country: "Bosnia & Herzegovina", timezones: ["Europe/Sarajevo"] },
  { country: "Botswana", timezones: ["Africa/Gaborone"] },
  {
    country: "Brazil",
    timezones: [
      "America/Araguaina",
      "America/Bahia",
      "America/Belem",
      "America/Boa_Vista",
      "America/Campo_Grande",
      "America/Cuiaba",
      "America/Eirunepe",
      "America/Fortaleza",
      "America/Maceio",
      "America/Manaus",
      "America/Noronha",
      "America/Porto_Velho",
      "America/Recife",
      "America/Rio_Branco",
      "America/Santarem",
      "America/Sao_Paulo",
    ],
  },
  { country: "Britain (UK)", timezones: ["Europe/London"] },
  { country: "British Indian Ocean Territory", timezones: ["Indian/Chagos"] },
  { country: "Brunei", timezones: ["Asia/Brunei"] },
  { country: "Bulgaria", timezones: ["Europe/Sofia"] },
  { country: "Burkina Faso", timezones: ["Africa/Ouagadougou"] },
  { country: "Burundi", timezones: ["Africa/Bujumbura"] },
  { country: "Cambodia", timezones: ["Asia/Phnom_Penh"] },
  { country: "Cameroon", timezones: ["Africa/Douala"] },
  {
    country: "Canada",
    timezones: [
      "America/Atikokan",
      "America/Blanc-Sablon",
      "America/Cambridge_Bay",
      "America/Creston",
      "America/Dawson",
      "America/Dawson_Creek",
      "America/Edmonton",
      "America/Fort_Nelson",
      "America/Glace_Bay",
      "America/Goose_Bay",
      "America/Halifax",
      "America/Inuvik",
      "America/Iqaluit",
      "America/Moncton",
      "America/Rankin_Inlet",
      "America/Regina",
      "America/Resolute",
      "America/St_Johns",
      "America/Swift_Current",
      "America/Toronto",
      "America/Vancouver",
      "America/Whitehorse",
      "America/Winnipeg",
    ],
  },
  { country: "Cape Verde", timezones: ["Atlantic/Cape_Verde"] },
  { country: "Caribbean NL", timezones: ["America/Kralendijk"] },
  { country: "Cayman Islands", timezones: ["America/Cayman"] },
  { country: "Central African Rep.", timezones: ["Africa/Bangui"] },
  { country: "Chad", timezones: ["Africa/Ndjamena"] },
  {
    country: "Chile",
    timezones: [
      "America/Coyhaique",
      "America/Punta_Arenas",
      "America/Santiago",
      "Pacific/Easter",
    ],
  },
  {
    country: "China",
    timezones: [
      "Asia/Shanghai",
      "Asia/Urumqi",
    ],
  },
  { country: "Christmas Island", timezones: ["Indian/Christmas"] },
  { country: "Cocos (Keeling) Islands", timezones: ["Indian/Cocos"] },
  { country: "Colombia", timezones: ["America/Bogota"] },
  { country: "Comoros", timezones: ["Indian/Comoro"] },
  {
    country: "Congo (Dem. Rep.)",
    timezones: [
      "Africa/Kinshasa",
      "Africa/Lubumbashi",
    ],
  },
  { country: "Congo (Rep.)", timezones: ["Africa/Brazzaville"] },
  { country: "Cook Islands", timezones: ["Pacific/Rarotonga"] },
  { country: "Costa Rica", timezones: ["America/Costa_Rica"] },
  { country: "Côte d’Ivoire", timezones: ["Africa/Abidjan"] },
  { country: "Croatia", timezones: ["Europe/Zagreb"] },
  { country: "Cuba", timezones: ["America/Havana"] },
  { country: "Curaçao", timezones: ["America/Curacao"] },
  {
    country: "Cyprus",
    timezones: [
      "Asia/Famagusta",
      "Asia/Nicosia",
    ],
  },
  { country: "Czech Republic", timezones: ["Europe/Prague"] },
  { country: "Denmark", timezones: ["Europe/Copenhagen"] },
  { country: "Djibouti", timezones: ["Africa/Djibouti"] },
  { country: "Dominica", timezones: ["America/Dominica"] },
  { country: "Dominican Republic", timezones: ["America/Santo_Domingo"] },
  { country: "East Timor", timezones: ["Asia/Dili"] },
  {
    country: "Ecuador",
    timezones: [
      "America/Guayaquil",
      "Pacific/Galapagos",
    ],
  },
  { country: "Egypt", timezones: ["Africa/Cairo"] },
  { country: "El Salvador", timezones: ["America/El_Salvador"] },
  { country: "Equatorial Guinea", timezones: ["Africa/Malabo"] },
  { country: "Eritrea", timezones: ["Africa/Asmara"] },
  { country: "Estonia", timezones: ["Europe/Tallinn"] },
  { country: "Eswatini (Swaziland)", timezones: ["Africa/Mbabane"] },
  { country: "Ethiopia", timezones: ["Africa/Addis_Ababa"] },
  { country: "Falkland Islands", timezones: ["Atlantic/Stanley"] },
  { country: "Faroe Islands", timezones: ["Atlantic/Faroe"] },
  { country: "Fiji", timezones: ["Pacific/Fiji"] },
  { country: "Finland", timezones: ["Europe/Helsinki"] },
  { country: "France", timezones: ["Europe/Paris"] },
  { country: "French Guiana", timezones: ["America/Cayenne"] },
  {
    country: "French Polynesia",
    timezones: [
      "Pacific/Gambier",
      "Pacific/Marquesas",
      "Pacific/Tahiti",
    ],
  },
  { country: "French S. Terr.", timezones: ["Indian/Kerguelen"] },
  { country: "Gabon", timezones: ["Africa/Libreville"] },
  { country: "Gambia", timezones: ["Africa/Banjul"] },
  { country: "Georgia", timezones: ["Asia/Tbilisi"] },
  {
    country: "Germany",
    timezones: [
      "Europe/Berlin",
      "Europe/Busingen",
    ],
  },
  { country: "Ghana", timezones: ["Africa/Accra"] },
  { country: "Gibraltar", timezones: ["Europe/Gibraltar"] },
  { country: "Greece", timezones: ["Europe/Athens"] },
  {
    country: "Greenland",
    timezones: [
      "America/Danmarkshavn",
      "America/Nuuk",
      "America/Scoresbysund",
      "America/Thule",
    ],
  },
  { country: "Grenada", timezones: ["America/Grenada"] },
  { country: "Guadeloupe", timezones: ["America/Guadeloupe"] },
  { country: "Guam", timezones: ["Pacific/Guam"] },
  { country: "Guatemala", timezones: ["America/Guatemala"] },
  { country: "Guernsey", timezones: ["Europe/Guernsey"] },
  { country: "Guinea", timezones: ["Africa/Conakry"] },
  { country: "Guinea-Bissau", timezones: ["Africa/Bissau"] },
  { country: "Guyana", timezones: ["America/Guyana"] },
  { country: "Haiti", timezones: ["America/Port-au-Prince"] },
  { country: "Honduras", timezones: ["America/Tegucigalpa"] },
  { country: "Hong Kong", timezones: ["Asia/Hong_Kong"] },
  { country: "Hungary", timezones: ["Europe/Budapest"] },
  { country: "Iceland", timezones: ["Atlantic/Reykjavik"] },
  { country: "India", timezones: ["Asia/Kolkata"] },
  {
    country: "Indonesia",
    timezones: [
      "Asia/Jakarta",
      "Asia/Jayapura",
      "Asia/Makassar",
      "Asia/Pontianak",
    ],
  },
  { country: "Iran", timezones: ["Asia/Tehran"] },
  { country: "Iraq", timezones: ["Asia/Baghdad"] },
  { country: "Ireland", timezones: ["Europe/Dublin"] },
  { country: "Isle of Man", timezones: ["Europe/Isle_of_Man"] },
  { country: "Israel", timezones: ["Asia/Jerusalem"] },
  { country: "Italy", timezones: ["Europe/Rome"] },
  { country: "Jamaica", timezones: ["America/Jamaica"] },
  { country: "Japan", timezones: ["Asia/Tokyo"] },
  { country: "Jersey", timezones: ["Europe/Jersey"] },
  { country: "Jordan", timezones: ["Asia/Amman"] },
  {
    country: "Kazakhstan",
    timezones: [
      "Asia/Almaty",
      "Asia/Aqtau",
      "Asia/Aqtobe",
      "Asia/Atyrau",
      "Asia/Oral",
      "Asia/Qostanay",
      "Asia/Qyzylorda",
    ],
  },
  { country: "Kenya", timezones: ["Africa/Nairobi"] },
  {
    country: "Kiribati",
    timezones: [
      "Pacific/Kanton",
      "Pacific/Kiritimati",
      "Pacific/Tarawa",
    ],
  },
  { country: "Korea (North)", timezones: ["Asia/Pyongyang"] },
  { country: "Korea (South)", timezones: ["Asia/Seoul"] },
  { country: "Kuwait", timezones: ["Asia/Kuwait"] },
  { country: "Kyrgyzstan", timezones: ["Asia/Bishkek"] },
  { country: "Laos", timezones: ["Asia/Vientiane"] },
  { country: "Latvia", timezones: ["Europe/Riga"] },
  { country: "Lebanon", timezones: ["Asia/Beirut"] },
  { country: "Lesotho", timezones: ["Africa/Maseru"] },
  { country: "Liberia", timezones: ["Africa/Monrovia"] },
  { country: "Libya", timezones: ["Africa/Tripoli"] },
  { country: "Liechtenstein", timezones: ["Europe/Vaduz"] },
  { country: "Lithuania", timezones: ["Europe/Vilnius"] },
  { country: "Luxembourg", timezones: ["Europe/Luxembourg"] },
  { country: "Macau", timezones: ["Asia/Macau"] },
  { country: "Madagascar", timezones: ["Indian/Antananarivo"] },
  { country: "Malawi", timezones: ["Africa/Blantyre"] },
  {
    country: "Malaysia",
    timezones: [
      "Asia/Kuala_Lumpur",
      "Asia/Kuching",
    ],
  },
  { country: "Maldives", timezones: ["Indian/Maldives"] },
  { country: "Mali", timezones: ["Africa/Bamako"] },
  { country: "Malta", timezones: ["Europe/Malta"] },
  {
    country: "Marshall Islands",
    timezones: [
      "Pacific/Kwajalein",
      "Pacific/Majuro",
    ],
  },
  { country: "Martinique", timezones: ["America/Martinique"] },
  { country: "Mauritania", timezones: ["Africa/Nouakchott"] },
  { country: "Mauritius", timezones: ["Indian/Mauritius"] },
  { country: "Mayotte", timezones: ["Indian/Mayotte"] },
  {
    country: "Mexico",
    timezones: [
      "America/Bahia_Banderas",
      "America/Cancun",
      "America/Chihuahua",
      "America/Ciudad_Juarez",
      "America/Hermosillo",
      "America/Matamoros",
      "America/Mazatlan",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
      "America/Ojinaga",
      "America/Tijuana",
    ],
  },
  {
    country: "Micronesia",
    timezones: [
      "Pacific/Chuuk",
      "Pacific/Kosrae",
      "Pacific/Pohnpei",
    ],
  },
  { country: "Moldova", timezones: ["Europe/Chisinau"] },
  { country: "Monaco", timezones: ["Europe/Monaco"] },
  {
    country: "Mongolia",
    timezones: [
      "Asia/Hovd",
      "Asia/Ulaanbaatar",
    ],
  },
  { country: "Montenegro", timezones: ["Europe/Podgorica"] },
  { country: "Montserrat", timezones: ["America/Montserrat"] },
  { country: "Morocco", timezones: ["Africa/Casablanca"] },
  { country: "Mozambique", timezones: ["Africa/Maputo"] },
  { country: "Myanmar (Burma)", timezones: ["Asia/Yangon"] },
  { country: "Namibia", timezones: ["Africa/Windhoek"] },
  { country: "Nauru", timezones: ["Pacific/Nauru"] },
  { country: "Nepal", timezones: ["Asia/Kathmandu"] },
  { country: "Netherlands", timezones: ["Europe/Amsterdam"] },
  { country: "New Caledonia", timezones: ["Pacific/Noumea"] },
  {
    country: "New Zealand",
    timezones: [
      "Pacific/Auckland",
      "Pacific/Chatham",
    ],
  },
  { country: "Nicaragua", timezones: ["America/Managua"] },
  { country: "Niger", timezones: ["Africa/Niamey"] },
  { country: "Nigeria", timezones: ["Africa/Lagos"] },
  { country: "Niue", timezones: ["Pacific/Niue"] },
  { country: "Norfolk Island", timezones: ["Pacific/Norfolk"] },
  { country: "North Macedonia", timezones: ["Europe/Skopje"] },
  { country: "Northern Mariana Islands", timezones: ["Pacific/Saipan"] },
  { country: "Norway", timezones: ["Europe/Oslo"] },
  { country: "Oman", timezones: ["Asia/Muscat"] },
  { country: "Pakistan", timezones: ["Asia/Karachi"] },
  { country: "Palau", timezones: ["Pacific/Palau"] },
  {
    country: "Palestine",
    timezones: [
      "Asia/Gaza",
      "Asia/Hebron",
    ],
  },
  { country: "Panama", timezones: ["America/Panama"] },
  {
    country: "Papua New Guinea",
    timezones: [
      "Pacific/Bougainville",
      "Pacific/Port_Moresby",
    ],
  },
  { country: "Paraguay", timezones: ["America/Asuncion"] },
  { country: "Peru", timezones: ["America/Lima"] },
  { country: "Philippines", timezones: ["Asia/Manila"] },
  { country: "Pitcairn", timezones: ["Pacific/Pitcairn"] },
  { country: "Poland", timezones: ["Europe/Warsaw"] },
  {
    country: "Portugal",
    timezones: [
      "Atlantic/Azores",
      "Atlantic/Madeira",
      "Europe/Lisbon",
    ],
  },
  { country: "Puerto Rico", timezones: ["America/Puerto_Rico"] },
  { country: "Qatar", timezones: ["Asia/Qatar"] },
  { country: "Réunion", timezones: ["Indian/Reunion"] },
  { country: "Romania", timezones: ["Europe/Bucharest"] },
  {
    country: "Russia",
    timezones: [
      "Asia/Anadyr",
      "Asia/Barnaul",
      "Asia/Chita",
      "Asia/Irkutsk",
      "Asia/Kamchatka",
      "Asia/Khandyga",
      "Asia/Krasnoyarsk",
      "Asia/Magadan",
      "Asia/Novokuznetsk",
      "Asia/Novosibirsk",
      "Asia/Omsk",
      "Asia/Sakhalin",
      "Asia/Srednekolymsk",
      "Asia/Tomsk",
      "Asia/Ust-Nera",
      "Asia/Vladivostok",
      "Asia/Yakutsk",
      "Asia/Yekaterinburg",
      "Europe/Astrakhan",
      "Europe/Kaliningrad",
      "Europe/Kirov",
      "Europe/Moscow",
      "Europe/Samara",
      "Europe/Saratov",
      "Europe/Ulyanovsk",
      "Europe/Volgograd",
    ],
  },
  { country: "Rwanda", timezones: ["Africa/Kigali"] },
  { country: "Samoa (American)", timezones: ["Pacific/Pago_Pago"] },
  { country: "Samoa (western)", timezones: ["Pacific/Apia"] },
  { country: "San Marino", timezones: ["Europe/San_Marino"] },
  { country: "Sao Tome & Principe", timezones: ["Africa/Sao_Tome"] },
  { country: "Saudi Arabia", timezones: ["Asia/Riyadh"] },
  { country: "Senegal", timezones: ["Africa/Dakar"] },
  { country: "Serbia", timezones: ["Europe/Belgrade"] },
  { country: "Seychelles", timezones: ["Indian/Mahe"] },
  { country: "Sierra Leone", timezones: ["Africa/Freetown"] },
  { country: "Singapore", timezones: ["Asia/Singapore"] },
  { country: "Slovakia", timezones: ["Europe/Bratislava"] },
  { country: "Slovenia", timezones: ["Europe/Ljubljana"] },
  { country: "Solomon Islands", timezones: ["Pacific/Guadalcanal"] },
  { country: "Somalia", timezones: ["Africa/Mogadishu"] },
  { country: "South Africa", timezones: ["Africa/Johannesburg"] },
  { country: "South Georgia & the South Sandwich Islands", timezones: ["Atlantic/South_Georgia"] },
  { country: "South Sudan", timezones: ["Africa/Juba"] },
  {
    country: "Spain",
    timezones: [
      "Africa/Ceuta",
      "Atlantic/Canary",
      "Europe/Madrid",
    ],
  },
  { country: "Sri Lanka", timezones: ["Asia/Colombo"] },
  { country: "St Barthelemy", timezones: ["America/St_Barthelemy"] },
  { country: "St Helena", timezones: ["Atlantic/St_Helena"] },
  { country: "St Kitts & Nevis", timezones: ["America/St_Kitts"] },
  { country: "St Lucia", timezones: ["America/St_Lucia"] },
  { country: "St Maarten (Dutch)", timezones: ["America/Lower_Princes"] },
  { country: "St Martin (French)", timezones: ["America/Marigot"] },
  { country: "St Pierre & Miquelon", timezones: ["America/Miquelon"] },
  { country: "St Vincent", timezones: ["America/St_Vincent"] },
  { country: "Sudan", timezones: ["Africa/Khartoum"] },
  { country: "Suriname", timezones: ["America/Paramaribo"] },
  { country: "Svalbard & Jan Mayen", timezones: ["Arctic/Longyearbyen"] },
  { country: "Sweden", timezones: ["Europe/Stockholm"] },
  { country: "Switzerland", timezones: ["Europe/Zurich"] },
  { country: "Syria", timezones: ["Asia/Damascus"] },
  { country: "Taiwan", timezones: ["Asia/Taipei"] },
  { country: "Tajikistan", timezones: ["Asia/Dushanbe"] },
  { country: "Tanzania", timezones: ["Africa/Dar_es_Salaam"] },
  { country: "Thailand", timezones: ["Asia/Bangkok"] },
  { country: "Togo", timezones: ["Africa/Lome"] },
  { country: "Tokelau", timezones: ["Pacific/Fakaofo"] },
  { country: "Tonga", timezones: ["Pacific/Tongatapu"] },
  { country: "Trinidad & Tobago", timezones: ["America/Port_of_Spain"] },
  { country: "Tunisia", timezones: ["Africa/Tunis"] },
  { country: "Turkey", timezones: ["Europe/Istanbul"] },
  { country: "Turkmenistan", timezones: ["Asia/Ashgabat"] },
  { country: "Turks & Caicos Is", timezones: ["America/Grand_Turk"] },
  { country: "Tuvalu", timezones: ["Pacific/Funafuti"] },
  { country: "Uganda", timezones: ["Africa/Kampala"] },
  {
    country: "Ukraine",
    timezones: [
      "Europe/Kyiv",
      "Europe/Simferopol",
    ],
  },
  { country: "United Arab Emirates", timezones: ["Asia/Dubai"] },
  {
    country: "United States",
    timezones: [
      "America/Adak",
      "America/Anchorage",
      "America/Boise",
      "America/Chicago",
      "America/Denver",
      "America/Detroit",
      "America/Indiana/Indianapolis",
      "America/Indiana/Knox",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Tell_City",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Juneau",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Los_Angeles",
      "America/Menominee",
      "America/Metlakatla",
      "America/New_York",
      "America/Nome",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/Phoenix",
      "America/Sitka",
      "America/Yakutat",
      "Pacific/Honolulu",
    ],
  },
  { country: "Uruguay", timezones: ["America/Montevideo"] },
  {
    country: "US minor outlying islands",
    timezones: [
      "Pacific/Midway",
      "Pacific/Wake",
    ],
  },
  {
    country: "Uzbekistan",
    timezones: [
      "Asia/Samarkand",
      "Asia/Tashkent",
    ],
  },
  { country: "Vanuatu", timezones: ["Pacific/Efate"] },
  { country: "Vatican City", timezones: ["Europe/Vatican"] },
  { country: "Venezuela", timezones: ["America/Caracas"] },
  { country: "Vietnam", timezones: ["Asia/Ho_Chi_Minh"] },
  { country: "Virgin Islands (UK)", timezones: ["America/Tortola"] },
  { country: "Virgin Islands (US)", timezones: ["America/St_Thomas"] },
  { country: "Wallis & Futuna", timezones: ["Pacific/Wallis"] },
  { country: "Western Sahara", timezones: ["Africa/El_Aaiun"] },
  { country: "Yemen", timezones: ["Asia/Aden"] },
  { country: "Zambia", timezones: ["Africa/Lusaka"] },
  { country: "Zimbabwe", timezones: ["Africa/Harare"] },
];

export function getTimezonesByCountry(country: string) {
  return (
    countryTimezones.find((item) => item.country === country)?.timezones ?? []
  );
}

export function getAllTimezones() {
  return Array.from(
    new Set(countryTimezones.flatMap((item) => item.timezones)),
  ).sort();
}

export function getCountryByTimezone(timezone: string) {
  return (
    countryTimezones.find((item) => item.timezones.includes(timezone))
      ?.country ?? ""
  );
}

export function isValidIanaTimezone(timezone: string) {
  try {
    Intl.DateTimeFormat(undefined, { timeZone: timezone });
    return true;
  } catch {
    return false;
  }
}

export function formatInTimezone(date: Date, timezone: string) {
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: timezone,
  }).format(date);
}

export function prepareBookingTimeForClientTimezone({
  clientTimezone,
  date,
  specialistTimezone,
}: {
  clientTimezone: string;
  date: Date;
  specialistTimezone: string;
}) {
  return {
    clientDisplayTime: formatInTimezone(date, clientTimezone),
    clientTimezone,
    specialistDisplayTime: formatInTimezone(date, specialistTimezone),
    specialistTimezone,
  };
}
